// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcTi7iQwuY4SG2sj6_Z-r9OB3mQZlfU8U',
    appId: '1:1057877852393:web:a2b296f091767be3ac7078',
    messagingSenderId: '1057877852393',
    projectId: 'mibdsheets82',
    authDomain: 'mibdsheets82.firebaseapp.com',
    storageBucket: 'mibdsheets82.firebasestorage.app',
    measurementId: 'G-3Z6Y6F5B2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyTAo-3oYA5ck-I4_vcpNik_KZjb4FbxI',
    appId: '1:1057877852393:android:7b58a79ef7877137ac7078',
    messagingSenderId: '1057877852393',
    projectId: 'mibdsheets82',
    storageBucket: 'mibdsheets82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAovSvv8a2m61sBsVPmPPqUYDOh4jJi5p0',
    appId: '1:1057877852393:ios:90559a173a1c0d79ac7078',
    messagingSenderId: '1057877852393',
    projectId: 'mibdsheets82',
    storageBucket: 'mibdsheets82.firebasestorage.app',
    iosBundleId: 'com.example.mibdSheets82',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAovSvv8a2m61sBsVPmPPqUYDOh4jJi5p0',
    appId: '1:1057877852393:ios:90559a173a1c0d79ac7078',
    messagingSenderId: '1057877852393',
    projectId: 'mibdsheets82',
    storageBucket: 'mibdsheets82.firebasestorage.app',
    iosBundleId: 'com.example.mibdSheets82',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcTi7iQwuY4SG2sj6_Z-r9OB3mQZlfU8U',
    appId: '1:1057877852393:web:e6c07352f7e29bebac7078',
    messagingSenderId: '1057877852393',
    projectId: 'mibdsheets82',
    authDomain: 'mibdsheets82.firebaseapp.com',
    storageBucket: 'mibdsheets82.firebasestorage.app',
    measurementId: 'G-WM53CRRDPH',
  );

}